// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // 실행중인 기기가 안드로이드 인지 아이폰인지 웹인지 firebase설정을 자동으로 골라주는 함수수
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC78Bdi7AOfVABVwZKswHpDAvnDXF0muhE',
    appId: '1:297154945940:web:77248ba71da413d80a2581',
    messagingSenderId: '297154945940',
    projectId: 'neon-fire-6f34c',
    authDomain: 'neon-fire-6f34c.firebaseapp.com',
    storageBucket: 'neon-fire-6f34c.firebasestorage.app',
    measurementId: 'G-2VW0JH3WC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPqIwYSuYrprE77vB4CHnxkXwLOHD7YYU',
    appId: '1:297154945940:android:96e7720e9513d1db0a2581',
    messagingSenderId: '297154945940',
    projectId: 'neon-fire-6f34c',
    storageBucket: 'neon-fire-6f34c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEm9LdV0tjmYrpI426f7P5EtdwQ4hwUOY',
    appId: '1:297154945940:ios:0531b6e820a647ef0a2581',
    messagingSenderId: '297154945940',
    projectId: 'neon-fire-6f34c',
    storageBucket: 'neon-fire-6f34c.firebasestorage.app',
    iosBundleId: 'com.example.neonFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEm9LdV0tjmYrpI426f7P5EtdwQ4hwUOY',
    appId: '1:297154945940:ios:0531b6e820a647ef0a2581',
    messagingSenderId: '297154945940',
    projectId: 'neon-fire-6f34c',
    storageBucket: 'neon-fire-6f34c.firebasestorage.app',
    iosBundleId: 'com.example.neonFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC78Bdi7AOfVABVwZKswHpDAvnDXF0muhE',
    appId: '1:297154945940:web:67a0ec6079a75da90a2581',
    messagingSenderId: '297154945940',
    projectId: 'neon-fire-6f34c',
    authDomain: 'neon-fire-6f34c.firebaseapp.com',
    storageBucket: 'neon-fire-6f34c.firebasestorage.app',
    measurementId: 'G-YE1NZXWYXF',
  );
}
